#!/bin/bash

# Vetting --- SEE pedantic script (./pedantic) for documented
# explanations about if statments (covered in day2.pdf, slide 28)


# Fetch the first parameter
if [ -z "$1" ] ; then 
	echo "USAGE: ./myscript { OUTFILE } " ;
	exit 1 ; 
elif [ -f "$1" ] ; then 
	echo -e "ERROR: File \"${1}\" already exists" ;
	exit 1 ;
fi


OUT="$1";


# Create the output file
touch ${OUT} ;


# Run the command on a delay
while true ; do
    netstat | grep "DGRAM" | wc -l >> ${OUT} ;
    sleep 1s ; 
done 




